In [2]:
import numpy as np

In [7]:
np.random.seed(2)

In [8]:
samples = np.random.normal(size=(4, 4))

In [9]:
samples

array([[-0.41675785, -0.05626683, -2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737,  0.50288142, -1.24528809],
       [-1.05795222, -0.90900761,  0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545,  0.53905832, -0.5961597 ]])

In [10]:
np.random.uniform((3,4))

array([1.29204941, 2.51728949])

In [ ]:
The data generation functions in numpy.random use a global random seed.
To avoid global state, you can use numpy.random.RandomState to create a random number generator isolated from others:

In [11]:
rng = np.random.RandomState(1234)
rng.randn(10) 

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [13]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [23]:
a= a.reshape((4, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [24]:
a.reshape((4, 2)).reshape((2, 4)) # not assigned to x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [25]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [39]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
One of the passed shape dimensions can be –1,
in which case the value used for that dimension will be inferred from the data: # 
    # means numpy column apnii marzee say daeydaega

SyntaxError: invalid syntax (<ipython-input-40-368ec638c047>, line 1)

In [42]:
arr=arr.reshape((5, -1)) 
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [21]:
arr.shape

(5, 3)

In [58]:
x = np.random.randn(4,5)

In [59]:
x

array([[ 0.49794015,  0.12650418, -1.41881055, -0.25177412, -1.54667461],
       [-2.08265194,  3.2797454 ,  0.97086132,  1.79259285, -0.42901332],
       [ 0.69619798,  0.69741627,  0.60151581,  0.00365949, -0.22824756],
       [-2.06961226,  0.61014409,  0.4234969 ,  1.11788673, -0.27424209]])

In [60]:
print(x.reshape((2,2,5))) # default row major mein 

[[[ 0.49794015  0.12650418 -1.41881055 -0.25177412 -1.54667461]
  [-2.08265194  3.2797454   0.97086132  1.79259285 -0.42901332]]

 [[ 0.69619798  0.69741627  0.60151581  0.00365949 -0.22824756]
  [-2.06961226  0.61014409  0.4234969   1.11788673 -0.27424209]]]


In [61]:
print(x.reshape((2,2,5),order ='F')) # F for column major

[[[ 0.49794015  0.12650418 -1.41881055 -0.25177412 -1.54667461]
  [ 0.69619798  0.69741627  0.60151581  0.00365949 -0.22824756]]

 [[-2.08265194  3.2797454   0.97086132  1.79259285 -0.42901332]
  [-2.06961226  0.61014409  0.4234969   1.11788673 -0.27424209]]]


In [56]:
x.reshape(2,2,-1)

array([[[ 2.55043824, -1.47317325, -1.02141473,  0.4323957 ,
         -0.32358007],
        [ 0.42382471,  0.79918   ,  1.26261366,  0.75196485,
         -0.99376098]],

       [[ 1.10914328, -1.76491773, -0.1144213 , -0.49817419,
         -1.06079904],
        [ 0.59166652, -0.18325657,  1.01985473, -1.48246548,
          0.84631189]]])

In [62]:
x.ravel() # one dimension mein ajayga

array([ 0.49794015,  0.12650418, -1.41881055, -0.25177412, -1.54667461,
       -2.08265194,  3.2797454 ,  0.97086132,  1.79259285, -0.42901332,
        0.69619798,  0.69741627,  0.60151581,  0.00365949, -0.22824756,
       -2.06961226,  0.61014409,  0.4234969 ,  1.11788673, -0.27424209])

In [63]:
x.flatten() # one dimension mein ajayga

array([ 0.49794015,  0.12650418, -1.41881055, -0.25177412, -1.54667461,
       -2.08265194,  3.2797454 ,  0.97086132,  1.79259285, -0.42901332,
        0.69619798,  0.69741627,  0.60151581,  0.00365949, -0.22824756,
       -2.06961226,  0.61014409,  0.4234969 ,  1.11788673, -0.27424209])

In [64]:
x = np.arange(20)

In [65]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [66]:
x.reshape(2,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [71]:
x=x.reshape((4,5),order = 'F')
print(x)

[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


In [72]:
x.reshape(2,2,5)

array([[[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17]],

       [[ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]]])

In [73]:
x.reshape((2,2,5),order='F') ######################################################3

array([[[ 0,  4,  8, 12, 16],
        [ 2,  6, 10, 14, 18]],

       [[ 1,  5,  9, 13, 17],
        [ 3,  7, 11, 15, 19]]])

In [74]:
 arr = np.arange(12).reshape((3, 4))

In [75]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
arr.ravel('F') # column say phelay cheezain leen

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [78]:
arr1= np.array([[1, 2, 3], [4, 5, 6]])

In [79]:
arr2= np.array([[7,8,9], [10,11,12]])

In [ ]:
concanate arr1,arr2 ko list kay square brackets mein # it takes list or tuple of array

In [80]:
np.concatenate([arr1, arr2], axis=0) # axis 0 rows increase

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [81]:
np.concatenate([arr1, arr2], axis=1) # axis 1 columns increase

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
vstack --> rows increase
hstack --> columns increase

In [82]:
np.vstack((arr1, arr2)) # rows increase # axis 0

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [83]:
np.hstack((arr1, arr2))  # columns increase # axis 1

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [84]:
arr = np.random.randn(5, 2)

In [107]:
print(arr)

[[ 1.74181219 -0.44750088]
 [-1.25542722  0.93816367]
 [-0.46834626 -1.25472031]
 [ 0.12482365  0.75650214]
 [ 0.24143963  0.49742565]]


In [ ]:
https://www.tutorialsandyou.com/python/numpy-split-in-python-76.html # splitting help

In [86]:
first, second, third = np.split(arr, [1, 3]) # >?????????????????????????????????????


In [87]:
first

array([[ 1.74181219, -0.44750088]])

In [88]:
second

array([[-1.25542722,  0.93816367],
       [-0.46834626, -1.25472031]])

In [89]:
third

array([[0.12482365, 0.75650214],
       [0.24143963, 0.49742565]])

In [ ]:
The value [1, 3] passed to np.split indicate the indices at which to split the array into pieces.

In [94]:
a = np.arange(9) 

print('First array:') 
print(a)
print('\n')  

print('Split the array in 3 equal-sized subarrays:')
b = np.split(a,3) 
print(b)
print('\n') 

print('Split the array at positions indicated in 1-D array:')
b = np.split(a,[4,7])
print(b)

First array:
[0 1 2 3 4 5 6 7 8]


Split the array in 3 equal-sized subarrays:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


Split the array at positions indicated in 1-D array:
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [99]:
x= np.array([1,2,3,4,5,5,4,3,2,1])

In [100]:
np.split(x,[2,5]) #arr[:2], arr[2:5], and arr[5:]

[array([1, 2]), array([3, 4, 5]), array([5, 4, 3, 2, 1])]

In [45]:
y =np.array([[1,2,3,4,5,5,4,3],[11,12,13,14,15,15,14,13]])

In [106]:
np.split(y,[4,6],axis=1) # ?????????????/

[array([[ 1,  2,  3,  4],
        [11, 12, 13, 14]]), array([[ 5,  5],
        [15, 15]]), array([[ 4,  3,  2,  1],
        [14, 13, 12, 11]])]

In [109]:
print(np.split(y,1,axis=0)) 

[array([[ 1,  2,  3,  4,  5,  5,  4,  3,  2,  1],
       [11, 12, 13, 14, 15, 15, 14, 13, 12, 11]])]


In [110]:
print(np.split(y,[1],axis=0))

[array([[1, 2, 3, 4, 5, 5, 4, 3, 2, 1]]), array([[11, 12, 13, 14, 15, 15, 14, 13, 12, 11]])]


In [46]:
print(np.split(y,2,axis=1)) # 2parts mein divide

[array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]]), array([[ 5,  5,  4,  3],
       [15, 15, 14, 13]])]


In [112]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [113]:
np.stack([arr1,arr2])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [116]:
np.vstack([arr1,arr2]) # vstack rows increase

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [117]:
np.hstack([arr1,arr2]) # hstack columns increase

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
Stacking helpers: r_ and c_  # see from book

In [118]:
arr = np.arange(3)

In [119]:
arr.repeat(3) # 3 times every element repeat

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [ ]:
By default, if you pass an integer, each element will be repeated that number of times.
If you pass an array of integers, each element can be repeated a different number of times:

In [120]:
 arr.repeat([2, 3, 4]) 

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [131]:
arr1 = np.random.randn(2, 2)
arr1

array([[ 1.33556617,  0.30262934],
       [-0.45422785,  0.51437072]])

In [132]:
arr1.repeat(2,axis = 1)

array([[ 1.33556617,  1.33556617,  0.30262934,  0.30262934],
       [-0.45422785, -0.45422785,  0.51437072,  0.51437072]])

In [133]:
arr1.repeat(2,axis = 0)

array([[ 1.33556617,  0.30262934],
       [ 1.33556617,  0.30262934],
       [-0.45422785,  0.51437072],
       [-0.45422785,  0.51437072]])

In [134]:
 arr1.repeat([2, 3], axis=0) # some repeat 2 times and some 3 times

array([[ 1.33556617,  0.30262934],
       [ 1.33556617,  0.30262934],
       [-0.45422785,  0.51437072],
       [-0.45422785,  0.51437072],
       [-0.45422785,  0.51437072]])

In [135]:
arr1.repeat([2, 3], axis=1) 

array([[ 1.33556617,  1.33556617,  0.30262934,  0.30262934,  0.30262934],
       [-0.45422785, -0.45422785,  0.51437072,  0.51437072,  0.51437072]])

In [139]:
arr1

array([[ 1.33556617,  0.30262934],
       [-0.45422785,  0.51437072]])

In [141]:
np.tile(arr1, 2) # entire array 2 times repeat

array([[ 1.33556617,  0.30262934,  1.33556617,  0.30262934],
       [-0.45422785,  0.51437072, -0.45422785,  0.51437072]])

In [142]:
np.tile(arr1, (2, 1)) # 2 times the array repaet

array([[ 1.33556617,  0.30262934],
       [-0.45422785,  0.51437072],
       [ 1.33556617,  0.30262934],
       [-0.45422785,  0.51437072]])

In [144]:
np.tile(arr1, (2, 2)) # 2 times repeat array + add it one time ahead

array([[ 1.33556617,  0.30262934,  1.33556617,  0.30262934],
       [-0.45422785,  0.51437072, -0.45422785,  0.51437072],
       [ 1.33556617,  0.30262934,  1.33556617,  0.30262934],
       [-0.45422785,  0.51437072, -0.45422785,  0.51437072]])

In [ ]:
The need to replicate or repeat arrays can be less common with NumPy than it is with other array programming frameworks like MATLAB.
One reason for this is that broadcasting often fills this need better, which is the subject of the next section.

In [143]:
import numpy as geek 
  
arr = geek.arange(4).reshape(2, 2) 
print("arr : \n", arr) 
  
a = 2  
b = 1  
repetitions = (a, b) 
print("\nRepeating arr : \n", geek.tile(arr, repetitions)) 
print("arr Shape : \n", geek.tile(arr, repetitions).shape) 
  
a = 3  
b = 2   
repetitions = (a, b) 
print("\nRepeating arr : \n", geek.tile(arr, repetitions)) 
print("arr Shape : \n", geek.tile(arr, repetitions).shape) 
  
a = 2
b = 3  
repetitions = (a, b) 
print("\nRepeating arr : \n", geek.tile(arr, repetitions)) 
print("arr Shape : \n", geek.tile(arr, repetitions).shape) 

arr : 
 [[0 1]
 [2 3]]

Repeating arr : 
 [[0 1]
 [2 3]
 [0 1]
 [2 3]]
arr Shape : 
 (4, 2)

Repeating arr : 
 [[0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]]
arr Shape : 
 (6, 4)

Repeating arr : 
 [[0 1 0 1 0 1]
 [2 3 2 3 2 3]
 [0 1 0 1 0 1]
 [2 3 2 3 2 3]]
arr Shape : 
 (4, 6)


In [145]:
array = [[5, 6, 2, 7, 1], 
         [4, 9, 2, 9, 3]] 
print("Original array : \n", array) 
  
# indices = [0, 4] 
print("\nTaking Indices\n", geek.take(array, [0, 4])) 
  
# indices = [0, 4] with axis = 1 
print("\nTaking Indices\n", geek.take(array, [0, 4], axis = 1))

Original array : 
 [[5, 6, 2, 7, 1], [4, 9, 2, 9, 3]]

Taking Indices
 [5 1]

Taking Indices
 [[5 1]
 [4 3]]


In [146]:
a = geek.arange(5) 
geek.put(a, [0, 2], [-44, -55]) # 0,2 per element put
print("After put : \n", a)

After put : 
 [-44   1 -55   3   4]


In [147]:
array = [[5, 6, 2, 7, 1], 
         [4, 9, 2, 9, 3]] 
print("Original array : \n", array) 
  
# indices = [0, 4] 
print("\nTaking Indices\n", geek.take(array, [0, 4])) # 0,4 say element take
  
# indices = [0, 4] with axis = 1 
print("\nTaking Indices\n", geek.take(array, [0, 4], axis = 1)) 


Original array : 
 [[5, 6, 2, 7, 1], [4, 9, 2, 9, 3]]

Taking Indices
 [5 1]

Taking Indices
 [[5 1]
 [4 3]]


In [ ]:
#see take and put from book also

In [5]:
arr1 = np.array([1, 2, 3], dtype=np.int32)

In [6]:
arr1.dtype 

dtype('int32')

In [8]:
float_arr = arr1.astype(np.float64)

In [9]:
float_arr

array([1., 2., 3.])

In [10]:
float_arr.dtype

dtype('float64')

In [11]:
arr1 # is still int because 
#Calling astype always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype

array([1, 2, 3])

In [12]:
arr1.dtype

dtype('int32')

In [13]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [14]:
numeric_strings.astype(float) # see next cell

array([ 1.25, -9.6 , 42.  ])

In [ ]:
If casting were to fail for some reason (like a string that cannot be converted to float64),
a ValueError will be raised. Here I was a bit lazy and wrote float instead of np.float64;
NumPy aliases the Python types to its own equivalent data dtypes. 

In [15]:
a = np.arange(10)

In [16]:
a[5:8]

array([5, 6, 7])

In [17]:
a[5:8]=12

In [18]:
a

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [ ]:
An important first distinction from Python’s built-in lists is that array slices are views on the original array.
This means that the data is not copied, and any modifications to the view will be reflected in the source array. 

In [20]:
arr_slice = a[5:8]

In [21]:
arr_slice

array([12, 12, 12])

In [22]:
arr_slice[1] = 12345

In [23]:
a

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [24]:
arr_slice[:] = 64 #64 assign to all values of slice

In [25]:
a

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [41]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) # 7

In [42]:
data = np.random.randn(7, 4)

In [43]:
 names == 'Bob' 

array([ True, False, False,  True, False, False, False])

In [44]:
data

array([[ 1.71749932,  0.15857175,  0.70167961,  1.1280977 ],
       [-1.56218973, -0.78150794, -1.62656388,  1.51036394],
       [ 0.22191343,  0.74849053,  1.7881059 ,  0.93761681],
       [ 0.45081363, -1.04289702,  1.8300507 , -1.11795676],
       [-1.56776748, -0.69467573,  0.60037852,  2.46864435],
       [-1.09686851, -0.7270309 , -0.48631113,  0.5061032 ],
       [ 0.93593252, -0.9109501 ,  1.15340714, -0.88978617]])

In [45]:
data[names=='Bob'] # jin row per true wo show

array([[ 1.71749932,  0.15857175,  0.70167961,  1.1280977 ],
       [ 0.45081363, -1.04289702,  1.8300507 , -1.11795676]])

In [46]:
data[~(names == 'Bob')] # condition invert

array([[-1.56218973, -0.78150794, -1.62656388,  1.51036394],
       [ 0.22191343,  0.74849053,  1.7881059 ,  0.93761681],
       [-1.56776748, -0.69467573,  0.60037852,  2.46864435],
       [-1.09686851, -0.7270309 , -0.48631113,  0.5061032 ],
       [ 0.93593252, -0.9109501 ,  1.15340714, -0.88978617]])

In [47]:
data[data < 0] = 0   # jahan per condition true wahan per zero ajayga

In [48]:
data

array([[1.71749932, 0.15857175, 0.70167961, 1.1280977 ],
       [0.        , 0.        , 0.        , 1.51036394],
       [0.22191343, 0.74849053, 1.7881059 , 0.93761681],
       [0.45081363, 0.        , 1.8300507 , 0.        ],
       [0.        , 0.        , 0.60037852, 2.46864435],
       [0.        , 0.        , 0.        , 0.5061032 ],
       [0.93593252, 0.        , 1.15340714, 0.        ]])

In [49]:
names != 'Joe'

array([ True, False,  True,  True,  True, False, False])

In [50]:
data[names != 'Joe'] = 7

In [51]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 1.51036394],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.5061032 ],
       [0.93593252, 0.        , 1.15340714, 0.        ]])

In [52]:
arr = np.empty((8, 4))

In [53]:
for i in range(8): 
    arr[i] = i


In [54]:
 arr 

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
To select out a subset of the rows in a particular order, 
you can simply pass a list or ndarray of integers specifying the desired order:

In [55]:
arr[[4, 3, 0, 6]] 

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [56]:
 arr[[-3, -5, -7]]  # -3 from backward i.e -1 is[7,7,7,7] , -2 is[6,6,6,6]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [67]:
 arr = np.arange(32).reshape((8, 4))

In [68]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [59]:
 arr[[1, 5, 7, 2], [0, 3, 1, 2]] #(1,0),(5,3).........

array([ 4, 23, 29, 10])

In [64]:

print(arr[[1,5,7,2]][:,[0,3,1,2]])

# 1[0,3,1,2],5[0,3,1,2],7[0,3,1,2],2[0,3,1,2]
#(1,0)(1,3)(1,1)(1,2)(5,0)(5,3)(5,1)(5,2)...............

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [65]:
print(arr[[1,5,7,2]][[0,3,1,2]]) #?????????????

[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]


In [69]:
print(arr[[1,5,7,2]][0,[0,3,1,2]]) # ??????//

[4 7 5 6]


In [70]:
t = arr.T # now 4 by 7
t

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [71]:
arr.transpose() # same as .T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [72]:
 np.dot(arr.T, arr) #matrix multiplication

array([[2240, 2352, 2464, 2576],
       [2352, 2472, 2592, 2712],
       [2464, 2592, 2720, 2848],
       [2576, 2712, 2848, 2984]])

In [47]:
ar = np.arange(16).reshape((2, 2, 4))

In [48]:
ar

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [76]:
ar.transpose((1, 0, 2)) #//??????????????

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [49]:
 ar.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [50]:
ar.swapaxes(2,1)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [5]:
a=np.array([1.0,2.1,3.0])
b = a.astype('int32')

In [6]:
b

array([1, 2, 3])

In [7]:
a # a remains same

array([1. , 2.1, 3. ])

In [8]:
arr2 = np.arange(9).reshape(3,3)

In [9]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
 arr2[:2] 

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
 arr2[:2, 1:] 

array([[1, 2],
       [4, 5]])

In [18]:
a=[1,2,3,4]
a[1:]

[2, 3, 4]

In [20]:
arr2[:2, 1:]

array([[1, 2],
       [4, 5]])

In [21]:
arr2[:, :1] 

array([[0],
       [3],
       [6]])

In [23]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
    

In [24]:
data[names == 'Bob', 2:] #columnn will be indexed too

array([[ 0.54375604, -1.38641692],
       [-1.81078121, -1.29474789]])

In [29]:
arr = np.random.randn(4, 4)
arr

array([[-0.17387453,  0.40347886,  0.45132377, -0.27772576],
       [ 1.31842877,  0.06553829,  0.48428144,  0.03900472],
       [ 1.4259133 ,  1.60117866, -2.12705554, -0.47002984],
       [ 1.60047307, -0.97973272,  0.41366193,  0.64051514]])

In [30]:
np.where(arr > 0, 2, arr) # false honay per wesay hee rahay

array([[-0.17387453,  2.        ,  2.        , -0.27772576],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        , -2.12705554, -0.47002984],
       [ 2.        , -0.97973272,  2.        ,  2.        ]])

In [35]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [36]:
arr1.sum(axis=0) #rows collapse and added

array([30, 34, 38, 42, 46])

In [37]:
arr1.sum(axis=1)  # columns collapse and added

array([10, 35, 60, 85])