In [4]:
%time
a = [1,2,3,4,5,6,7,8,9,10]
ans = []

for i in a:
    ans.append(i*5)

print(ans)

Wall time: 0 ns
[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


In [2]:
import numpy as np

In [5]:
%time # time showing for computation
a = np.array([1,2,3,4,5,6,7,8,9,10])
a*5

Wall time: 0 ns


array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [12]:
numpyArray = np.array([22,44.5,55,66])
print(numpyArray)

[22.  44.5 55.  66. ]


In [2]:
numpyArray = np.array([22,44,55,66])
print(numpyArray)

[22 44 55 66]


In [9]:
numpyArray = np.array([22,44,55,66],dtype = 'float32')
print(numpyArray)
print(type(numpyArray)) # n dimensions

[22. 44. 55. 66.]
<class 'numpy.ndarray'>


In [14]:
numpyArray = np.array([22.5,44,55,66],dtype = "int32") #each  number occupies 32 bits
print(numpyArray)

[22 44 55 66]


In [15]:
numpyArray = np.array([22.5,44,55,66],dtype = np.int8)
print(numpyArray)

[22 44 55 66]


In [2]:
randomArray = np.random.randn(10) # normal distribution numbers per


In [8]:
0.77878682 + 0.77878682 
print(1.55757364 + 1.55757364)

3.11514728


In [3]:
print(randomArray)

[ 0.85989349  0.38700161  1.28327783 -1.71078123 -0.11092273 -0.28778773
  0.93457844 -0.12229709 -0.17815645  0.90219655]


In [20]:
randomArray.ndim

1

In [21]:
randomArray.shape # the no of elements give the shape or columns

(10,)

In [ ]:
array>>>>vector
matrix >>>> tensor

In [47]:
one_D = np.array([9],[7])

TypeError: data type not understood

In [41]:
one_D.ndim

1

In [6]:
_D = np.array([[9]])
_D.ndim

2

In [7]:
_D.shape

(1, 1)

In [8]:
_D.size

1

In [46]:
two_D = np.array([[9],[8]])
two_D.ndim

2

In [30]:
two_D = np.array([[1,2,3],[4,5,6]])

In [31]:
print(two_D)

[[1 2 3]
 [4 5 6]]


In [32]:
two_D.size

6

In [33]:
two_D.shape

(2, 3)

In [4]:
zeroD = np.array(100) # scalar value has been  passed 

In [5]:
zeroD

array(100)

In [6]:
zeroD.ndim #scalar

0

In [7]:
zeroD.shape

()

In [8]:
miscD = np.array([99])
print(miscD)
print(miscD.ndim)
print(miscD.shape)
print(miscD.size)

[99]
1
(1,)
1


In [19]:
miscD = np.array([ [[99] ,[90]] ])
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[99]
  [90]]]
3
(1, 2, 1)


In [23]:
misc_D1 = np.array([[90,91],[78,90]])
print(misc_D1)
print(misc_D1.ndim)
print(misc_D1.size)
print(misc_D1.shape)

[[90 91]
 [78 90]]
2
4
(2, 2)


In [48]:
miscD = np.array([ [[99] , [98]] ])
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[99]
  [98]]]
3
(1, 2, 1)


In [15]:
miscD = np.array([ [ [99],[98] ] ,  [ [99],[98] ] ]) # x per 1, y per 1 , z per 1
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[99]
  [98]]

 [[99]
  [98]]]
3
(2, 2, 1)


In [18]:
miscD = np.array([ [ [99],[98],[97] ]  ]) # x per 1, y per 1 , z per 1
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[99]
  [98]
  [97]]]
3
(1, 3, 1)


In [20]:
miscD = np.array([ [[99],[98]] , [[98],[97]] ]) # x per 1, y per 1 , z per 1
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[99]
  [98]]

 [[98]
  [97]]]
3
(2, 2, 1)


In [49]:
miscD = np.array([[[  [[99],[98]] , [[99],[98]]  ]]]) 
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[[[99]
    [98]]

   [[99]
    [98]]]]]
5
(1, 1, 2, 2, 1)


In [39]:
a = np.arange(10) 
print(a) # vector

[0 1 2 3 4 5 6 7 8 9]


In [41]:
a = np.arange(12).reshape(4,3)
print(a) # matrix

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [43]:
flat = np.ravel(a) # again vector
print(flat)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [44]:
flat = flat.reshape(12)
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
z = np.array([22,33,44,55,66,77])

In [46]:
z

array([22, 33, 44, 55, 66, 77])

In [48]:
rZ = z.reshape(2,3)
rZ

array([[22, 33, 44],
       [55, 66, 77]])

In [50]:
fZ = np.ravel(rZ)
fZ

array([22, 33, 44, 55, 66, 77])

In [29]:
two_D = np.arange(36).reshape(6,6)

In [30]:
two_D

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [32]:
three_D = two_D.reshape(3,3,4)
three_D

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [35]:
three_D = two_D.reshape(2,2,9)
three_D

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35]]])

In [58]:
rebacktoD = three_D.reshape(6,6)
rebacktoD

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [11]:
threeD = np.array([ [[1,2,3],[4,5,6],[7,8,9]] ,[[3,6,8],[8,7,6],[9,8,7]] ])
print(threeD)
print(threeD.ndim)
print(threeD.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[3 6 8]
  [8 7 6]
  [9 8 7]]]
3
(2, 3, 3)


In [ ]:
[ [[],[],[]] , [[],[],[]]  ]

In [62]:
two_D + two_D

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46],
       [48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70]])

In [63]:
two_D - two_D

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [64]:
two_D / two_D

C:\Users\abeer\OneDrive\Music\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [65]:
 two_D * two_D # element wise operation , mirror multiplication , mirror addition , mirror subtraction but only for same shape

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [66]:
m1 = np.arange(12).reshape(4,3)
m2 = np.random.randn(16).reshape(4,4)

m1 + m2 # shape should be same

ValueError: operands could not be broadcast together with shapes (4,3) (4,4) 

In [68]:
m3 = np.arange(18).reshape(3,6)

In [69]:
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [70]:
m1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [71]:
m1@m3 # normal matrix multiplication when shape not same

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [72]:
m1 * m3

ValueError: operands could not be broadcast together with shapes (4,3) (3,6) 

In [73]:
np.dot(m1,m3)

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [74]:
m1.dot(m3)

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [75]:
m1.dtype

dtype('int32')

In [76]:
zeeroes = np.zeros(4)

In [77]:
zeeroes

array([0., 0., 0., 0.])

In [78]:
zeeroes = np.zeros(4,dtype = "int8")
zeeroes

array([0, 0, 0, 0], dtype=int8)

In [79]:
zeeroes = np.zeros((4,5),dtype = "int8")
zeeroes

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [80]:
ones = np.ones((5,5),dtype = "int8")
ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [24]:
ones = np.ones(5,5) # two round brackets should be 
ones * 50

TypeError: data type not understood

In [25]:
ones = np.ones((5,5)) # two round brackets should be 
ones * 50

array([[50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.]])

In [27]:
fulll = np.full((4,4),100)
fulll

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [84]:
empty = np.empty((4,4,4))

In [85]:
empty # can give the garbage values 

array([[[6.36598936e-314, 0.00000000e+000, 4.94065646e-324,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]],

       [[0.00000000e+000, 8.48798316e-311, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         1.98564983e-320],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+0

In [87]:
like = np.zeros_like(m3) # will give the zero matrix of m3's dimension
like

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [97]:
i = np.eye(3,3) # determinant will be 1
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [98]:
i = i.astype('int') # changes datatype
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# Basic indexing and Slicing

In [100]:
alist = [99,90,89,90]

In [102]:
 i = alist[0]
print(type(i))

<class 'int'>


In [103]:
i = alist[0:2]
print(type(i))

<class 'list'>


In [2]:
two_d = np.arange(36).reshape(6,6)
print(two_d)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [106]:
two_d[3,2]

20

In [107]:
two_d[3][2]

20

In [108]:
#two_d[row,column]
#two_d[start:end,start:end]
two_d[2:5,1:4]

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [5]:
two_d[5:,3:4]

array([[33]])

In [6]:
two_d[5,3:4]

array([33])

In [111]:
two_d[1:2,2:5]

array([[ 8,  9, 10]])

In [7]:
arr2D = np.array([[22,33,44],[55,66,77],[88,99,100]])

In [8]:
arr2D

array([[ 22,  33,  44],
       [ 55,  66,  77],
       [ 88,  99, 100]])

In [9]:
arr2D[:2]

array([[22, 33, 44],
       [55, 66, 77]])

In [10]:
arr2D[:2,:1]

array([[22],
       [55]])

In [12]:
arr3D = np.array([[[100,200,300],[400,500,600],[700,800,900]]])

In [13]:
arr3D

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [14]:
arr3D.shape # 1 2D

(1, 3, 3)

In [15]:
arr3D[0]

array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])

In [16]:
arr3D[0][2]

array([700, 800, 900])

In [17]:
arr3D[0][2][0]

700

In [18]:
arr3D[0,2,0]

700

In [19]:
arr3D

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [20]:
arr3D = np.array([ [[100,200,300],[400,500,600],[700,800,900]] ,[[1,2,3],[4,5,6],[7,8,9]] ])

In [21]:
arr3D

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]],

       [[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]]])

In [22]:
arr3D[0,:2]

array([[100, 200, 300],
       [400, 500, 600]])

In [23]:
arr3D[0,:2,1:]

array([[200, 300],
       [500, 600]])

In [24]:
arr2D = np.array([[2,4,6,8,10],[1,2,3,4,5],[4,0,6,2,5],[6,6,1,5,3],[7,5,1,6,5],[8,2,4,9,7]])

In [28]:
arr2D

array([[ 2,  4,  6,  8, 10],
       [ 1,  2,  3,  4,  5],
       [ 4,  0,  6,  2,  5],
       [ 6,  6,  1,  5,  3],
       [ 7,  5,  1,  6,  5],
       [ 8,  2,  4,  9,  7]])

In [27]:
arr2D[2:4,1:4]

array([[0, 6, 2],
       [6, 1, 5]])

In [30]:
arr2D = np.arange(36).reshape(6,6)

In [33]:
arr2D = np.arange(1,37).reshape(6,6)

In [34]:
arr2D

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [35]:
arr2D[2:4,2:]

array([[15, 16, 17, 18],
       [21, 22, 23, 24]])

In [36]:
arr2D[2]

array([13, 14, 15, 16, 17, 18])

In [38]:
arr2D[2:3,0:6] # correct slicing

array([[13, 14, 15, 16, 17, 18]])

In [40]:
arr2D[4:5,0:6]

array([[25, 26, 27, 28, 29, 30]])

In [41]:
arr2D[4:5,:]

array([[25, 26, 27, 28, 29, 30]])

In [42]:
arr2D[4:5,]

array([[25, 26, 27, 28, 29, 30]])

In [43]:
arr2D[4:5]

array([[25, 26, 27, 28, 29, 30]])

In [44]:
arr2D[,2]

SyntaxError: invalid syntax (<ipython-input-44-9627f647835b>, line 1)

In [45]:
arr2D[:,2]

array([ 3,  9, 15, 21, 27, 33])

In [47]:
arr2D[1:5,]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [48]:
arr2D[2:4,5] # 1 dimension mein answer

array([18, 24])

In [51]:
arr2D[2:4,5:] # 2 dimension mein answer

array([[18],
       [24]])

In [50]:
arr2D[2:4,-1]

array([18, 24])

In [55]:
arr2D[:,::2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [57]:
arr2D[::2,::2] # start of row: end of row : stepping

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

# 2nd class

# boolean indexing

In [11]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [12]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [5]:
data = np.random.randn(7,4)

In [6]:
data

array([[-1.78862068, -0.48847494,  0.15412564, -1.11935   ],
       [-0.52448214,  0.97704372,  1.02649095,  2.59441174],
       [ 0.26286673,  0.97459061,  2.05981488,  0.49854558],
       [-1.39854266, -1.25579728,  0.81396785,  0.14083943],
       [ 0.2800311 , -0.08089934,  1.84735687,  0.63442673],
       [ 0.21279476, -1.44391309, -0.05748466, -0.35300502],
       [ 1.28988269, -1.64276937, -1.00534911, -0.35901663]])

In [7]:
data>1

array([[False, False, False, False],
       [False, False,  True,  True],
       [False, False,  True, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [8]:
data[data>1]

array([1.02649095, 2.59441174, 2.05981488, 1.84735687, 1.28988269])

In [13]:
print(names == "Bob")
data[names=="Bob"] # 2 rows will come due to true has occured 2 times

[ True False False  True False False False]


array([[-1.78862068, -0.48847494,  0.15412564, -1.11935   ],
       [-1.39854266, -1.25579728,  0.81396785,  0.14083943]])

In [67]:
data[True,False,False,False,False,True,False] # yeh numpy array nhi pass hoe  hae

array([], shape=(0, 7, 4), dtype=float64)

In [14]:
boolean_array = np.array([True,False,False,False,False,True,False],dtype = 'bool')
print(boolean_array)
data[boolean_array] # ab numpy array pass hoe hae

[ True False False False False  True False]


array([[-1.78862068, -0.48847494,  0.15412564, -1.11935   ],
       [ 0.21279476, -1.44391309, -0.05748466, -0.35300502]])

In [77]:
condition = names!= "Bob"

In [73]:
data[condition]

array([[-1.26197369, -0.25215466,  1.49962765,  0.61749955],
       [ 0.14137535,  0.2050059 , -1.71185474, -1.02379853],
       [-2.23847616, -0.42426552,  0.0565205 , -0.6001609 ],
       [ 0.21838908, -0.81840493, -0.5117258 , -1.18950109],
       [ 2.93007181, -1.51098763, -0.39561528, -0.15484458]])

In [74]:
data[~condition] # ~ true ko false aur false ko true kardaeta hae 

array([[ 1.74668678,  0.94468891,  0.35823932, -1.33870547],
       [-0.91166226, -0.27062267, -1.20113115,  0.13061544]])

In [75]:
data

array([[ 1.74668678,  0.94468891,  0.35823932, -1.33870547],
       [-1.26197369, -0.25215466,  1.49962765,  0.61749955],
       [ 0.14137535,  0.2050059 , -1.71185474, -1.02379853],
       [-0.91166226, -0.27062267, -1.20113115,  0.13061544],
       [-2.23847616, -0.42426552,  0.0565205 , -0.6001609 ],
       [ 0.21838908, -0.81840493, -0.5117258 , -1.18950109],
       [ 2.93007181, -1.51098763, -0.39561528, -0.15484458]])

In [78]:
data[~condition,3]

array([-1.33870547,  0.13061544])

In [79]:
data[condition,1:3]

array([[-0.25215466,  1.49962765],
       [ 0.2050059 , -1.71185474],
       [-0.42426552,  0.0565205 ],
       [-0.81840493, -0.5117258 ],
       [-1.51098763, -0.39561528]])

In [82]:
data = np.arange(28).reshape(7,4)

In [83]:
print(data)
print(condition)
data[condition,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[False  True  True False  True  True  True]


array([[ 5,  6],
       [ 9, 10],
       [17, 18],
       [21, 22],
       [25, 26]])

In [86]:
print(data)
print(~condition)
data[~condition,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[ True False False  True False False False]


array([[ 1,  2],
       [13, 14]])

In [87]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [89]:
condition = (names=="Bob") | (names =="Joe")
condition

array([ True,  True, False,  True, False,  True,  True])

In [90]:
data[condition]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

# Fancy Indexing


In [15]:
arr = np.empty((8,4)) # gives garbage value empty sometimes

In [16]:
for i in range(8):
    arr[i] = i

In [17]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [18]:
arr[[1,2,3]]

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [19]:
arr[[4,0,1,8]] # fourth row phelay ajay phirr zero aur phir 1 row phir 7 row
#kisii array ka subset nikalana hae tou row numbers daey diyayayy
# ie subset of rows

IndexError: index 8 is out of bounds for axis 0 with size 8

In [20]:
arr[[4,0,1,7]]

array([[4., 4., 4., 4.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [7., 7., 7., 7.]])

In [21]:
arr[[-4,-8,-7,-1]]

array([[4., 4., 4., 4.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [7., 7., 7., 7.]])

In [103]:
arr[[4,0,1,2],[2,3,0,1]]
#(4,2),(0,3),(1,0),(2,1)

array([4., 0., 1., 2.])

In [24]:
arr = np.arange(32).reshape(8,4)

print(arr)

arr[[1,5,7,2]][:,[0,3,1,2]] 

# 1[0,3,1,2],5[0,3,1,2],7[0,3,1,2],2[0,3,1,2]
#(1,0)(1,3)(1,1)(1,2)(5,0)(5,3)(5,1)(5,2)...............

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [25]:
arr = np.arange(32).reshape(8,4)

print(arr)

arr[[1,5,7,2]][0,[0,3,1,2]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([4, 7, 5, 6])

In [108]:
t = arr.T # now 4 by 7
t

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [109]:
arr.transpose()

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [110]:
arr.sort()

In [111]:
a = [22,33,44,55,77,55]
a

[22, 33, 44, 55, 77, 55]

In [112]:
st = set(a)
st # repetative items ko discard

{22, 33, 44, 55, 77}

In [113]:
aset = {11,12,11,14,14}
aset

{11, 12, 14}

In [28]:
arr = np.arange(10)
np.save('some_array',arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [118]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [119]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [121]:
np.concatenate([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [122]:
np.concatenate([arr1,arr2],axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [123]:
np.concatenate([arr1,arr2],axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [124]:
np.stack([arr1,arr2])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [125]:
np.vstack([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [126]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [129]:
arr = np.arange(36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [130]:
np.vsplit(arr,3)


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [133]:
np.hsplit(arr,3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

# HOME

# book

In [3]:
arr = np.random.randn(5,4)

In [4]:
import numpy as np

In [4]:
arr

array([[ 1.2621942 , -1.2597182 , -1.89197482, -0.51126528],
       [-0.66475717, -0.15676842, -2.55329935,  1.4018843 ],
       [ 0.3767926 ,  0.68049206,  0.82179045, -1.39802069],
       [-0.54119167,  0.27400658, -0.79019519,  0.02455906],
       [-1.20338377, -0.78441885,  1.10217162,  0.50708192]])

In [5]:
arr.mean()

-0.26520103094689645

In [6]:
np.mean(arr)

-0.26520103094689645

In [7]:
arr.sum()

-5.304020618937929

In [8]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr1.sum(axis = 0)

array([5, 7, 9])

In [12]:
arr1.sum(axis = 1)

array([ 6, 15])

# Assignment

In [14]:
a = np.linspace(0,1,8)
print(a)

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


In [15]:
0.14285714 + 0.14285714

0.28571428

In [19]:
zeeroes = np.zeros(24)
zeeroes = zeeroes.reshape(2,3,4)
zeeroes

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [5]:
zeeroes =np.array( [[[0,0,0,0],[0,0,0,0],[0,0,0,0]],[[0,0,0,0],[0,0,0,0],[0,0,0,0]]])
print(zeeroes)
print(zeeroes.shape)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
(2, 3, 4)


In [20]:
onees = np.ones(24)
onees =onees.reshape(2,3,4)
onees

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [6]:
ones =np.array( [[[1,1,1,1],[1,1,1,1],[1,1,1,1]],[[1,1,1,1],[1,1,1,1],[1,1,1,1]]])
print(ones)
print(ones.shape)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
(2, 3, 4)


In [22]:
a = np.arange(0,999)
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [22]:
a = np.array([2,3.2,5.5,-6.4,-2.2,2.4])
print(a)

[ 2.   3.2  5.5 -6.4 -2.2  2.4]


In [23]:
a[1]

3.2

In [24]:
a[1:4]

array([ 3.2,  5.5, -6.4])

In [25]:
a = np.array([[2,3.2,5.5,-6.4,-2.2,2.4],[1,22,4,0.1,5.3,-9],[3,1,2.1,21,1.1,-2]])
print(a)

[[ 2.   3.2  5.5 -6.4 -2.2  2.4]
 [ 1.  22.   4.   0.1  5.3 -9. ]
 [ 3.   1.   2.1 21.   1.1 -2. ]]


In [28]:
print(a[:,3])
print(a[1:4,0:4])
print(a[1:,2])

[-6.4  0.1 21. ]
[[ 1.  22.   4.   0.1]
 [ 3.   1.   2.1 21. ]]
[4.  2.1]


In [30]:
arr = np.array[[x for x in range(4)],[ y for y in range(10,14)]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [37]:
a = [x for x in range(4)]
b = [ y for y in range(10,14)]

c = np.array([a,b])
print(c)
print(np.shape(c))
print(np.size(c))
print(c.max())
print(c.min())

[[ 0  1  2  3]
 [10 11 12 13]]
(2, 4)
8
13
0


In [42]:
print(c.reshape(2,2,2))
print(c.T)
print(c.ravel())
c = c.astype('float') # changes datatype
print(c)

[[[ 0  1]
  [ 2  3]]

 [[10 11]
  [12 13]]]
[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]]
[ 0  1  2  3 10 11 12 13]
[[ 0.  1.  2.  3.]
 [10. 11. 12. 13.]]


In [45]:
d = np.arange(1,21)
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [48]:
array = np.arange(1,10)
array = array * 3
print(array)

[ 3  6  9 12 15 18 21 24 27]


In [51]:
A= np.arange(1,9).reshape(2,4)
print(A)

[[1 2 3 4]
 [5 6 7 8]]


In [52]:
B = np.array([1,2])
print(B)

[1 2]


# BOOK

In [1]:
import numpy as np

In [6]:
arr = np.array([0, 1, 2 ,3, 4, 5 ,6, 7, 8 ,9])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [3]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr.cumsum(axis = 0))                      

[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]


In [4]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr.cumsum())                    

[ 0  1  3  6 10 15 21 28 36]


In [8]:
arr = np.random.randn(100)
print(arr)
print((arr > 0).sum())  # sum()  gives no.of true values in arr or no of positive values in arr


[ 1.89014216 -0.22913318  0.60442082  0.1304862  -2.10888241 -1.05525394
 -0.5083108   0.11817182 -0.15848817 -0.11160831 -1.21278595 -0.11455593
  1.39773198  0.22436832  0.41944477 -1.43432705 -0.55980134 -0.74788272
  1.45283806  1.15238652 -0.86033283 -1.03841888  0.02613527  0.7644595
  0.44228505  0.93735526  0.16825665  0.2259768   0.13197461 -2.67057364
 -0.30994806 -1.83837875  1.61128505 -0.4559324   1.03131354  1.15624944
 -0.39308052  1.00188593 -0.32813026 -1.76705392  0.10743897  0.33305418
 -0.93367888  0.36053551 -0.22678992 -0.68877409 -0.8603978   0.56970485
  0.20514415  1.49282527 -0.6447214  -1.176876    1.56966725 -1.20904134
  0.25034555 -0.07972664  0.39268599  0.46875955  1.25123762  0.35774387
  0.482792   -0.8615279  -0.86192484 -1.34858388 -0.78046705 -0.64431181
  0.52322786  0.40948404  0.35853355  0.63914859 -1.30231769 -0.16601924
 -0.67549695  0.79063722  0.56224025  1.30909097  0.35725137  0.23387002
  1.25790265 -0.65244373  0.59606365 -1.27680755 -0.

In [9]:
bools = np.array([False, False , True , False])  # any() checks if any one or more values are true
bools.any()

True

In [10]:
bools = np.array([False, False , False , False])  # any() checks if any one or more values are true
bools.any()

False

In [13]:
bools = np.array([False, False , False , False])  # all() checks if all values are true
bools.all()

False

In [15]:
bools = np.array([False, False , True , False])   # all() checks if all values are true
bools.all()

False

In [16]:
bools = np.array([True , True , True , True])   # all() checks if all values are true
bools.all()

True

In [17]:
large_arr = np.random.randn(1000)
large_arr.sort()

In [18]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
np.unique(names) # return sorted unique values


array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [19]:
# in python , we did
sorted(set(names))

['Bob', 'Joe', 'Will']

In [28]:
values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6]) # checks if element of first array present in second or not , returns boolean array

array([ True, False, False,  True,  True, False,  True])

In [15]:
arr = np.arange(10)
np.save('some_array',arr)

In [16]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr = np.arange(10)
arr1 = np.arange(20)
np.savez('array_archive',a=arr,b =arr1) # .savez can save the multiple arrays in uncompressed state by keyword arguments

In [18]:
array =np.load('array_archive.npz')

In [19]:
array['a'] # give the key

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.savez_compressed('array_compressed.npz',a=arr,b =arr1)#.savez_compressed can save the multiple arrays in compressed state by keyword arguments

In [21]:
a_z = np.load('array_compressed.npz')
print(a_z['a'])

[0 1 2 3 4 5 6 7 8 9]


In [14]:
print(b)

[1 2]


In [29]:
np.ones(3)

array([1., 1., 1.])

# 3rd class

In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3]])
print(x.shape)
y = np.array([[4],[5]])
print(y.shape)

(1, 3)
(2, 1)


In [5]:
s = np.broadcast_arrays(x,y)
print(s)

[array([[1, 2, 3],
       [1, 2, 3]]), array([[4, 4, 4],
       [5, 5, 5]])]


In [6]:
x,y = np.broadcast_arrays(x,y)

In [7]:
print(x)
print(y)

[[1 2 3]
 [1 2 3]]
[[4 4 4]
 [5 5 5]]


In [8]:
print(np.broadcast_arrays(x+y))

[array([[5, 6, 7],
       [6, 7, 8]])]
